CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE ROLE bank_owner;
GRANT ALL PRIVILEGES ON DATABASE bank to bank_owner;

CREATE SCHEMA main;
GRANT ALL PRIVILEGES ON SCHEMA main TO bank_owner;

ALTER DEFAULT PRIVILEGES IN SCHEMA main GRANT ALL PRIVILEGES ON TABLES TO bank_owner;